// Pixel-art generado en runtime: cada sprite es un mapa de caracteres + paleta.
// Se rasteriza una vez con Graphics y queda como textura nearest-neighbor (nítida).
window.MZ = window.MZ || {};
(() => {
  MZ.PIXEL_SPRITES = {
    heroe: {
      pal: { H: 0x6b3e1f, P: 0xffd9b3, E: 0x111111, C: 0x00cfff, c: 0x0088aa, L: 0x223344, B: 0x553311, S: 0xd7e3ea, G: 0xcc8800 },
      map: [
        '...HHHHH....',
        '..HHHHHHH..S',
        '..HPPPPPH..S',
        '..HPEPPEH..S',
        '..HPPPPPH..S',
        '...PPPPP...S',
        '..CCCCCCC..S',
        '.CcCCCCCcC.G',
        '.C.CCCCC.CG.',
        '...CCCCC....',
        '...LL.LL....',
        '...BB.BB....',
      ],
    },
    heroePinas: {
      pal: { H: 0x6b3e1f, P: 0xffd9b3, E: 0x111111, C: 0x00cfff, c: 0x0088aa, L: 0x223344, B: 0x553311 },
      map: [
        '...HHHHH....',
        '..HHHHHHH...',
        '..HPPPPPH...',
        '..HPEPPEH...',
        '..HPPPPPH...',
        '...PPPPP....',
        '..CCCCCCC...',
        '.CcCCCCCcC..',
        '.P.CCCCC.P..',
        '...CCCCC....',
        '...LL.LL....',
        '...BB.BB....',
      ],
    },
    heroeArco: {
      pal: { H: 0x6b3e1f, P: 0xffd9b3, E: 0x111111, C: 0x00cfff, c: 0x0088aa, L: 0x223344, B: 0x553311, M: 0x8a5a2b, S: 0xcccccc },
      map: [
        '...HHHHH...S',
        '..HHHHHHH.M.',
        '..HPPPPPH.M.',
        '..HPEPPEH.M.',
        '..HPPPPPHM..',
        '...PPPPP.M..',
        '..CCCCCCCM..',
        '.CcCCCCCcM..',
        '.C.CCCCC.M..',
        '...CCCCC..M.',
        '...LL.LL..M.',
        '...BB.BB...S',
      ],
    },
    heroeBfg: {
      pal: { H: 0x6b3e1f, P: 0xffd9b3, E: 0x111111, C: 0x00cfff, c: 0x0088aa, L: 0x223344, B: 0x553311, G: 0x33ff66, M: 0x2a2a33 },
      map: [
        '...HHHHH....',
        '..HHHHHHH...',
        '..HPPPPPH...',
        '..HPEPPEH...',
        '..HPPPPPH...',
        '...PPPPP....',
        '..CCCCCCMM..',
        '.CcCCCCMGGM.',
        '.C.CCCCMGGM.',
        '...CCCC.MM..',
        '...LL.LL....',
        '...BB.BB....',
      ],
    },
    escudoMini: {
      pal: { B: 0xffd700, A: 0x9d6bff, a: 0x6a44b8 },
      map: [
        'BBBBBB',
        'BAAaAB',
        'BAaAAB',
        'BAAAAB',
        '.BAAB.',
        '..BB..',
      ],
    },
    critico: {
      pal: { P: 0xd8c8a8, H: 0x888899, E: 0x111111, A: 0x222233, a: 0x333344, W: 0xffffff, N: 0xccaa66 },
      map: [
        '...HHHHHH...',
        '..HHHHHHHH..',
        '..HPPPPPPH..',
        '..WEWPPWEW..',
        '..HPPPPPPH..',
        '...PPPPPP...',
        '..AAAAAAAA..',
        '.AAaAAAAaAA.',
        '.AAAAAAAAAN.',
        '.AaAAAAAaAN.',
        '...AA..AA.N.',
        '...AA..AA...',
      ],
    },
    djtigre: {
      pal: { P: 0xc8a878, N: 0x222233, E: 0x111111, A: 0xff8800, a: 0xcc6600, F: 0xff00ff, C: 0x00ffff },
      map: [
        '..N.NNNN.N..',
        '..NNNNNNNN..',
        '..NPPPPPPN..',
        '..NPEPPEPN..',
        '..NPPPPPPN..',
        '...PPPPPP...',
        '..AAAAAAAA..',
        '.AAaAFCAaAA.',
        '.AAAAFCAAAA.',
        '.AaAAFCAAaA.',
        '...AA..AA...',
        '...AA..AA...',
      ],
    },
    rata: {
      pal: { R: 0x8a8a92, r: 0x6e6e76, P: 0xff9eb5, E: 0xff2244, W: 0xeeeeee },
      map: [
        '............',
        '............',
        '............',
        '..RR....RR..',
        '.RPPR..RPPR.',
        '.RRRRRRRRRr.',
        'RRERRRRRRRrP',
        'RRRRRRRRRr.P',
        'RWRRRRRRRr.P',
        '.RRr.RRr...P',
        '...........P',
        '............',
      ],
    },
    slime: {
      pal: { G: 0x66ff99, g: 0x33cc66, E: 0x0a3318, W: 0xccffdd },
      map: [
        '............',
        '............',
        '............',
        '....GGGG....',
        '..GGGGGGGG..',
        '.GWGGGGGGGG.',
        '.GWGGGGGGGG.',
        'GGGGEGGGEGGG',
        'GGGGEGGGEGGG',
        'GGGGGGGGGGGG',
        '.gggggggggg.',
        '............',
      ],
    },
    esqueleto: {
      pal: { W: 0x9ad89a, w: 0x6aa86a, E: 0xff3344 },
      map: [
        '...WWWWWW...',
        '..WWWWWWWW..',
        '..WEEWWEEW..',
        '..WWWWWWWW..',
        '...WwWWwW...',
        '....W..W....',
        '.WWWWWWWWWW.',
        '..W.wWWw.W..',
        '..W.WWWW.W..',
        '....w..w....',
        '...WW..WW...',
        '............',
      ],
    },
    fantasma: {
      pal: { G: [0xffb8d4, 0.75], g: [0xe88fb4, 0.6], E: 0x661133, M: [0x661133, 0.8] },
      map: [
        '....GGGG....',
        '..GGGGGGGG..',
        '.GGGGGGGGGG.',
        '.GGEEGGEEGG.',
        '.GGGGGGGGGG.',
        '.GGGGMMGGGG.',
        '.GGGGGGGGGG.',
        '.GGGGGGGGGG.',
        '.GGGGGGGGGG.',
        '.gG.GgG.GgG.',
        '.g...g...g..',
        '............',
      ],
    },
    ojo: {
      pal: { W: 0x2a2a33, V: 0xff2222, I: 0x4488ff, P: 0x111111, T: 0x8a96a4 },
      map: [
        '....WWWW....',
        '..WWWWWWWW..',
        '.WWWVWWWVWW.',
        '.WWIIIIWWWW.',
        'WWIIPPIIWWVW',
        'WWIIPPIIWWWW',
        '.WWIIIIWWWW.',
        '.WVWWWWWWWW.',
        '..WWWWWWWW..',
        '....WWWW....',
        '..T...T..T..',
        '............',
      ],
    },
    vibora: {
      pal: { V: 0x2ecc40, v: 0x1d8f2c, Y: 0xffe14d, T: 0xff3344 },
      map: [
        '....VVVV....',
        '...VVVVVV...',
        '...VYVVYV...',
        '...VVVVVV...',
        '..T.VVVV....',
        '..T..VVV....',
        '....VVVv....',
        '...VVVv.....',
        '..VVVv..VV..',
        '..VVVVVVVV..',
        '...vVVVVv...',
        '............',
      ],
    },
    arquero: {
      pal: { W: 0x55555f, w: 0x3c3c46, E: 0xffe14d, B: 0x8a5a2b },
      map: [
        '...WWWWWW..B',
        '..WWWWWWW.B.',
        '..WEEWWEEWB.',
        '..WWWWWWW.B.',
        '...WWWW...B.',
        '....W..W..B.',
        '.WWWWWWWWBB.',
        '..W.wWWw.B..',
        '..W.WWWW.B..',
        '....w..w....',
        '...WW..WW...',
        '............',
      ],
    },
    rataBlanca: {
      pal: { R: 0xf5f5ff, r: 0xd0d0e8, P: 0xffb6c1, E: 0x4488ff, W: 0xffffff },
      map: [
        '............',
        '............',
        '............',
        '..RR....RR..',
        '.RPPR..RPPR.',
        '.RRRRRRRRRr.',
        'RRERRRRRRRrP',
        'RRRRRRRRRr.P',
        'RWRRRRRRRr.P',
        '.RRr.RRr...P',
        '...........P',
        '............',
      ],
    },
    golem: {
      pal: { M: 0x222230, m: 0x3a3a48, C: 0x8a96a4, c: 0x55555f, E: 0xff8800 },
      map: [
        '.MMMMMMMMMM.',
        '.MmCCMMCCmM.',
        '.MCcCMMCcCM.',
        '.MmCCMMCCmM.',
        '.MMMMMMMMMM.',
        '.MMEMMMMEMM.',
        '.MMMMMMMMMM.',
        '.MmCCCCCCmM.',
        '.MCccccccCM.',
        '.MmCCCCCCmM.',
        '.MMMMMMMMMM.',
        '..mm....mm..',
      ],
    },
    vampiro: {
      pal: { N: 0x1a1a2e, P: 0xe8e0d8, E: 0xff2222, C: 0x8b0000, c: 0x5c0000, W: 0xffffff },
      map: [
        '...NNNNNN...',
        '..NNNNNNNN..',
        '..NPPPPPPN..',
        '..NPEPPEPN..',
        '..NPPPPPPN..',
        '...PWPPWP...',
        '..CCCCCCCC..',
        '.CCcCCCCcCC.',
        '.CCCCCCCCCC.',
        '.CcCCCCCCcC.',
        '..CCCCCCCC..',
        '...CC..CC...',
      ],
    },
    payaso: {
      pal: { B: 0xffffff, R: 0xff2244, E: 0x111111, V: 0x44cc44, A: 0x3366ff, Y: 0xffdd00 },
      map: [
        '..R..Y..A...',
        '...BBBBBB...',
        '..BBBBBBBB..',
        '..BEBBBBEB..',
        '..BBBRRBBB..',
        '...BRRRRB...',
        '..VVVVVVVV..',
        '.VAVAVAVAVA.',
        '.VVVVVVVVVV.',
        '..VVVVVVVV..',
        '...VV..VV...',
        '..YY....YY..',
      ],
    },
    nieto: {
      pal: { H: 0x6b3e1f, P: 0xffd9b3, E: 0x111111, A: 0xc0c8d0, a: 0x8a96a4, L: 0x223344 },
      map: [
        '...HHHHH....',
        '..HHHHHHH...',
        '..HPPPPPH...',
        '..HPEPPEH...',
        '..HPPPPPH...',
        '...PPPPP....',
        '..AAAAAAA...',
        '.AAaAAAaAA..',
        '.AAAAAAAAA..',
        '.AaAAAAAaA..',
        '...LL.LL....',
        '...AA.AA....',
      ],
    },
    fundador: {
      pal: { F: 0xffd700, H: 0xe8e8e8, P: 0xffd9b3, E: 0x111111, W: 0xfff8dc, C: 0x222230, L: 0x8a5a2b, l: 0x5d3a1e },
      map: [
        '......F.....',
        '...HHHHF....',
        '..HHHHHH....',
        '...PPPPP....',
        '...PEPPE....',
        '...WPPPW....',
        '..WWWWWW....',
        '...WWWW..L..',
        '..CCCCC.lL..',
        '.CCCCCC.lL..',
        '..CCCC..l...',
        '...C..C.....',
      ],
    },
    pombero: {
      pal: { S: 0xc9a14a, s: 0x9a7836, P: 0xb07a4a, E: 0x111111, F: 0x3b2b20, f: 0x2a1d15 },
      map: [
        '....SSSS....',
        '..SSSSSSSS..',
        '.SsSsSsSsSs.',
        '....PPPP....',
        '...PEPPEP...',
        '...PPPPPP...',
        '..FFFFFFFF..',
        '.FfFFFFFFfF.',
        '.F.FFFFFF.F.',
        '...FfFFfF...',
        '...FF..FF...',
        '............',
      ],
    },
    jefe: {
      pal: { H: 0xffaa00, D: 0xcc2244, d: 0x881122, E: 0xffff00, M: 0x110000 },
      map: [
        '.H........H.',
        '.HH......HH.',
        '..DDDDDDDD..',
        '.DDDDDDDDDD.',
        '.DDEEDDDEED.',
        '.DDDDDDDDDD.',
        '.DDMMMMMMDD.',
        '.DdDDDDDDdD.',
        '..DDDDDDDD..',
        '.DD.DDDD.DD.',
        '.d..DddD..d.',
        '....D..D....',
      ],
    },
    // ---- NPCs ----
    mercader: {
      pal: { H: 0x444455, P: 0xffd9b3, E: 0x111111, M: 0x442211, O: 0x4a5d3a, o: 0x36452a, L: 0x223344, B: 0x553311 },
      map: [
        '...HHHHHH...',
        '..HHHHHHHH..',
        '...PPPPPP...',
        '...PEPPEP...',
        '...PPPPPP...',
        '...PMMMMP...',
        '..OOOOOOOO..',
        '.OOooOOooOO.',
        '.OOOOOOOOOO.',
        '.OOooOOooOO.',
        '...LL..LL...',
        '...BB..BB...',
      ],
    },
    morena: {
      pal: { V: 0x8a2be2, v: 0x5a1c99, P: 0xe8b88a, H: 0x1a1a2e, E: 0x33ff88, L: 0xff4477, D: 0xb14cff, d: 0x8a2be2 },
      map: [
        '.....VV.....',
        '....VVVV....',
        '...VvVVvV...',
        '.VVVVVVVVVV.',
        '..HPPPPPPH..',
        '..HPEPPEPH..',
        '..HPPPPPPH..',
        '..HPPLLPPH..',
        '..HDDDDDDH..',
        '..HDdDDdDH..',
        '...DDDDDD...',
        '..DDDDDDDD..',
      ],
    },
    bardo: {
      pal: { F: 0xff2222, H: 0x6b4a2b, P: 0xffd9b3, E: 0x111111, W: 0xe8e8e8, C: 0x222230, L: 0xa0522d, l: 0x7a3d20 },
      map: [
        '......F.....',
        '...HHHHF....',
        '..HHHHHH....',
        '...PPPPP....',
        '...PEPPE....',
        '...WPPPW....',
        '..WWWWWW....',
        '...WWWW..L..',
        '..CCCCC.lL..',
        '.CCCCCC.lL..',
        '..CCCC..l...',
        '...C..C.....',
      ],
    },
    rodrigo: {
      pal: { H: 0x222222, P: 0xffd9b3, E: 0x111111, A: 0x9aa5b1, a: 0x6b7684, L: 0x223344, B: 0x553311 },
      map: [
        '...HHHHH....',
        '..HHHHHHH...',
        '...PPPPP....',
        '...PEPPE....',
        '...PPPPP....',
        '..AAAAAAA...',
        '.AAaAAAaAA..',
        '.AAAAAAAAA..',
        '.A.AaaAA.A..',
        '...AAAAA....',
        '...LL.LL....',
        '...BB.BB....',
      ],
    },
    esperanza: {
      pal: { N: 0x2a2a3a, n: 0x3e3e52, P: 0xf0c8a0, E: 0x99ccff, L: 0xff2255 },
      map: [
        '...NNNNNN...',
        '..NNNNNNNN..',
        '..NPPPPPPN..',
        '..NPEPPEPN..',
        '..NPPPPPPN..',
        '..NPPLLPPN..',
        '...NNNNNN...',
        '..NNNNNNNN..',
        '.NNNnNNnNNN.',
        '.NNNNNNNNNN.',
        '..NnNNNNnN..',
        '.NNNNNNNNNN.',
      ],
    },
    nona: {
      pal: { P: 0xf0c8a0, H: 0xe8e8e8, E: 0x333333, V: 0x8866aa, v: 0x664488, A: 0xffffff, L: 0x553311 },
      map: [
        '...HHHHHH...',
        '..HHHHHHHH..',
        '..HPPPPPPH..',
        '..HPEPPEPH..',
        '..HPPPPPPH..',
        '...PPLLPP...',
        '..VVVVVVVV..',
        '.VVAVVVVAVV.',
        '.VVVVVVVVVV.',
        '.VvVVVVVVvV.',
        '..VVVVVVVV..',
        '..VVV..VVV..',
      ],
    },
    tahur: {
      pal: { N: 0x222230, P: 0xd8a878, E: 0x111111, B: 0xcc2244, C: 0x333344, c: 0x222233, W: 0xffffff, G: 0xffd700 },
      map: [
        '...NNNNNN...',
        '..NNNNNNNN..',
        '...PPPPPP...',
        '...PEPPEP...',
        '...PPPPPP...',
        '...PPBBPP...',
        '..CCCCCCCC..',
        '.CCWCCCCWCC.',
        '.CcCCGGCCcC.',
        '.CCCCCCCCCC.',
        '...CC..CC...',
        '...CC..CC...',
      ],
    },
    herrero: {
      pal: { P: 0xc88858, H: 0x442211, E: 0x111111, D: 0x556677, d: 0x445566, M: 0x8a5a2b, A: 0x9aa5b1 },
      map: [
        '...HHHHHH..A',
        '..HHHHHHH..A',
        '...PPPPPP..A',
        '...PEPPEP..A',
        '...PPPPPP.AA',
        '...PPPPPP.MA',
        '..DDDDDDD.M.',
        '.DDdDDDDdDM.',
        '.DDDDDDDDDM.',
        '.DdDDDDDdDM.',
        '...DD..DD...',
        '...DD..DD...',
      ],
    },
    mosquito: {
      pal: { K: 0x222230, W: [0xccddee, 0.7], R: 0xcc2222 },
      map: [
        '............',
        '..W......W..',
        '..WW....WW..',
        '...WKKKKW...',
        '..KKKKKKKK..',
        '.RKKKKKKKK..',
        'R..KKKKKK...',
        '....KK.KK...',
        '....K...K...',
        '............',
        '............',
        '............',
      ],
    },
    brisa: {
      pal: { H: 0x3a2a1a, P: 0xe8b88a, E: 0x111111, C: 0xff8800, c: 0xcc6600, W: 0xffffff, L: 0x223344 },
      map: [
        '...HHHHHH...',
        '..HHHHHHHH..',
        '..HPPPPPPH..',
        '..HPEPPEPH..',
        '..HPPPPPPH..',
        '...PPPPPP...',
        '..CCCCCCCC..',
        '.CCWWWWWWCC.',
        '.CcWCCCCWcC.',
        '.CCCCCCCCCC.',
        '...LL..LL...',
        '...CC..CC...',
      ],
    },
    nuan: {
      pal: { H: 0x111118, P: 0xe8c89a, E: 0x111111, T: 0xff66aa, t: 0xcc4488, S: 0xffffff },
      map: [
        '...HHHHHH...',
        '..HHHHHHHH..',
        '..HPPPPPPH..',
        '..HPEPPEPH..',
        '..HPPPPPPH..',
        '.HHPPPPPPHH.',
        '.HHTTTTTTHH.',
        '..HTtTTtTH..',
        '..TTTTTTTT..',
        '...SSSSSS...',
        '...PP..PP...',
        '...TT..TT...',
      ],
    },
    monje: {
      pal: { M: 0xff8822, m: 0xcc6611, P: 0xd8b890, p: 0xb89870, E: 0x111111, W: 0xffe14d },
      map: [
        '....W..W....',
        '...PPPPPP...',
        '..PPpPPpPP..',
        '..PPPPPPPP..',
        '..PPEPPEPP..',
        '...PPPPPP...',
        '..MMMMMMMM..',
        '.MmMMMMMMmM.',
        '.MMMMMMMMMM.',
        '.MmMMMMMMmM.',
        '..MMMMMMMM..',
        '...MM..MM...',
      ],
    },
    tuktukero: {
      pal: { C: 0x2255cc, P: 0xc8a878, E: 0x111111, V: 0xffe14d, v: 0xcc9911, L: 0x223344 },
      map: [
        '..CCCCCCCC..',
        '..CCCCCCCC..',
        '...PPPPPP...',
        '...PEPPEP...',
        '...PPPPPP...',
        '...PPPPPP...',
        '..VVVVVVVV..',
        '.VvVCCCCVvV.',
        '.VVVCCCCVVV.',
        '.VvVVVVVVvV.',
        '...LL..LL...',
        '...CC..CC...',
      ],
    },
    lola: {
      pal: { H: 0xb14cff, h: 0x8a2be2, P: 0xe8b88a, E: 0x111111, D: 0xff2244, d: 0xcc1133, G: 0xffd700 },
      map: [
        '...HHHHHH...',
        '..HHHHHHHH..',
        '..HPPPPPPH..',
        '..HPEPPEPH..',
        '..HPPPPPPH..',
        '.HHPPPPPPHH.',
        '..DDDDDDDD..',
        '.DdDGDDGDdD.',
        '.DDDDDDDDDD.',
        '..DdDDDDdD..',
        '...PP..PP...',
        '...DD..DD...',
      ],
    },
    mochilero: {
      pal: { H: 0xe8c84a, P: 0xffd9b3, E: 0x111111, T: 0x44ccaa, M: 0xcc4422, m: 0x992c11, L: 0x8a5a2b },
      map: [
        '...HHHHH..M.',
        '..HHHHHHH.M.',
        '..HPPPPPHMM.',
        '..HPEPPEHMM.',
        '..HPPPPPHMM.',
        '...PPPPP.Mm.',
        '..TTTTTTTMm.',
        '..TTTTTTTM..',
        '..TTTTTTT...',
        '...LLLLL....',
        '...PP..PP...',
        '...LL..LL...',
      ],
    },
    heladero: {
      pal: { W: 0xf0f0f4, w: 0xc8c8d0, P: 0xc8a878, E: 0x111111, R: 0xff66aa, C: 0xc8965a, L: 0x223344 },
      map: [
        '...WWWWWW...',
        '..WWWWWWWW..',
        '..WPPPPPPW..',
        '..WPEPPEPW..',
        '..WPPPPPPW..',
        '...PPPPPP.R.',
        '..WWWWWWWWR.',
        '.WwWWWWWWwC.',
        '.WWWWWWWWWC.',
        '.WwWWWWWWw..',
        '...LL..LL...',
        '...WW..WW...',
      ],
    },
    influencer: {
      pal: { H: 0xffe08a, P: 0xe8b88a, E: 0x111111, F: 0xff44aa, f: 0xcc2288, K: 0x222230, J: 0x3a5a7a },
      map: [
        '...HHHHHH...',
        '..HHHHHHHH..',
        '..HPPPPPPH..',
        '..HPEPPEPH..',
        '..HPPPPPPH..',
        '.HHPPPPPPHH.',
        '..FFFFFFFK..',
        '.FfFFFFFfK..',
        '..FFFFFFF...',
        '...JJJJJJ...',
        '...PP..PP...',
        '...FF..FF...',
      ],
    },
    fotografo: {
      pal: { H: 0x442211, P: 0xd8a878, E: 0x111111, A: 0xff6644, a: 0x44aaff, K: 0x222230, k: 0x4488ff, L: 0x223344 },
      map: [
        '...HHHHHH...',
        '..HHHHHHHH..',
        '..HPPPPPPH..',
        '..HPEPPEPH..',
        '..HPPPPPPH..',
        '...PPPPPP...',
        '..AAaAAaAA..',
        '.AAKKKKKAaA.',
        '.AaKkkKKAAA.',
        '.AAKKKKKaAA.',
        '...LL..LL...',
        '...AA..AA...',
      ],
    },
    cocodrilo: {
      pal: { S: 0xc8b078, s: 0xa08850, P: 0xd8a878, E: 0x111111, G: 0x44aa44, L: 0x223344 },
      map: [
        '..SSSSSSSS..',
        '.SSSSSSSSSS.',
        '...PPPPPP...',
        '...PEPPEP...',
        '...PPPPPP...',
        '...PPPPPP...',
        '..SSSSSSSS..',
        '.SsSSSSSSsS.',
        '.SSSSSSSSSS.',
        '.SsSSSSSSsG.',
        '...LL..LLGG.',
        '...SS..SS.G.',
      ],
    },
    pitmaster: {
      pal: { H: 0xff2222, P: 0xe8b88a, E: 0x111111, W: 0xffffff, w: 0xcccccc, D: 0x8b4513, T: 0x888899, L: 0x223344 },
      map: [
        '...HHHHHH...',
        '..HHHHHHHH..',
        '..HPPPPPPH..',
        '..HPEPPEPH..',
        '..HPPPPPPH..',
        '...PDDDDP...',
        '..WWWWWWWW..',
        '.WWwWWWWwWT.',
        '.WWWWWWWWWT.',
        '.WwWWWWWWwT.',
        '...LL..LL...',
        '...WW..WW...',
      ],
    },
    cowboy: {
      pal: { S: 0xd8c8a0, s: 0xb0a078, P: 0xe8b890, E: 0x111111, J: 0x3a5a7a, j: 0x2a4a66, G: 0xffd700, L: 0x553311 },
      map: [
        '.SSSSSSSSSS.',
        '.sSSSSSSSSs.',
        '...SSSSSS...',
        '...PPPPPP...',
        '...PEPPEP...',
        '...PPPPPP...',
        '..JJJJJJJJ..',
        '.JjJGGGGJjJ.',
        '.JJJJGGJJJJ.',
        '.JjJJJJJJjJ.',
        '...LL..LL...',
        '...JJ..JJ...',
      ],
    },
    porrista: {
      pal: { H: 0x6b3e1f, P: 0xe8b88a, E: 0x111111, U: 0x2255cc, u: 0xffffff, R: 0xffd700, L: 0xe8b88a },
      map: [
        '.RR.....RR..',
        'RRRR...RRRR.',
        '.RRHHHHHRR..',
        '..HHHHHHH...',
        '..HPEPPEH...',
        '..HPPPPPH...',
        '...PPPPP....',
        '..UUUUUUU...',
        '.UuUUUUuUU..',
        '..UUUUUUU...',
        '...uuuuu....',
        '...LL.LL....',
      ],
    },
    camionero: {
      pal: { C: 0xcc2222, c: 0xffffff, P: 0xd8a878, E: 0x111111, M: 0x442211, Q: 0x8a2222, q: 0x5a1515, L: 0x3a5a7a },
      map: [
        '..CCCCCCCC..',
        '..CCccccCC..',
        '...PPPPPP...',
        '...PEPPEP...',
        '...PMMMMP...',
        '...PPPPPP...',
        '..QqQQqQQq..',
        '.QQqQQqQQqQ.',
        '.QqQQqQQqQQ.',
        '.QQqQQqQQqQ.',
        '...LL..LL...',
        '...QQ..QQ...',
      ],
    },
    dt: {
      pal: { K: 0x222230, P: 0xd8a878, E: 0x111111, V: 0x2a8a2a, v: 0x1d5d1d, W: 0xffffff, M: 0x442211 },
      map: [
        '...KKKKKK...',
        '..KKKKKKKK..',
        '...PPPPPP...',
        '...PEPPEP...',
        '...PMMMMP...',
        '...PPPPPP...',
        '..VVVVVVVV..',
        '.VvVWWWWVvV.',
        '.VVVVVVVVVV.',
        '.VvVVVVVVvV.',
        '...KK..KK...',
        '...VV..VV...',
      ],
    },
    mucama: {
      pal: { N: 0x222230, P: 0xe8b88a, E: 0x111111, W: 0xffffff, w: 0xd8d8e0, H: 0x442211, L: 0x223344 },
      map: [
        '....WWWW....',
        '...HHHHHH...',
        '..HHHHHHHH..',
        '..HPEPPEPH..',
        '..HPPPPPPH..',
        '...PPPPPP...',
        '..NNNNNNNN..',
        '.NNWWWWWWNN.',
        '.NNWwWWwWNN.',
        '.NNWWWWWWNN.',
        '...LL..LL...',
        '...NN..NN...',
      ],
    },
    jardinero: {
      pal: { S: 0xd8c878, P: 0xc8a878, E: 0x111111, V: 0x2a8a2a, v: 0x1d5d1d, G: 0x55ee55, L: 0x553311 },
      map: [
        '..SSSSSSSS..',
        '.SSSSSSSSSS.',
        '...PPPPPP...',
        '...PEPPEP...',
        '...PPPPPP...',
        '...PPPPPP.G.',
        '..VVVVVVVGG.',
        '.VvVVVVVVG..',
        '.VVVVVVVVV..',
        '.VvVVVVvVV..',
        '...LL..LL...',
        '...VV..VV...',
      ],
    },
    detective: {
      pal: { N: 0x4a4338, n: 0x36322a, P: 0xd8c8a8, E: 0x111111, M: 0x2a261e, L: 0x223344 },
      map: [
        '..MMMMMMMM..',
        '.MMMMMMMMMM.',
        '...PPPPPP...',
        '...PEPPEP...',
        '...PPPPPP...',
        '..NNNNNNNN..',
        '.NnNNNNNNnN.',
        '.NNNNNNNNNN.',
        '.NnNNNNNNnN.',
        '.NNNNNNNNNN.',
        '...LL..LL...',
        '...NN..NN...',
      ],
    },
    cuervo: {
      pal: { K: 0x1a1a22, k: 0x2e2e3a, Y: 0xffcc44, E: 0xff4444 },
      map: [
        '............',
        '....KK......',
        '...KKKK.....',
        '..KKEKKY....',
        '..KKKKK.....',
        '.KKKKKKKK...',
        'KKKKKKKKKK..',
        '.kKKKKKKKKK.',
        '..KKKKKKkK..',
        '...KKKKK....',
        '....Y..Y....',
        '............',
      ],
    },
    groupie: {
      pal: { H: 0xcc4488, P: 0xe8b88a, E: 0x111111, N: 0x1a1a22, G: 0xffd700, L: 0x3a5a7a },
      map: [
        '...HHHHHH...',
        '..HHHHHHHH..',
        '..HPPPPPPH..',
        '..HPEPPEPH..',
        '..HPPPPPPH..',
        '.HHPPPPPPHH.',
        '..NNNNNNNN..',
        '.NNNGGGGNNN.',
        '.NNGNNNNGNN.',
        '.NNNGGGGNNN.',
        '...LL..LL...',
        '...NN..NN...',
      ],
    },
    tatuador: {
      pal: { H: 0x111118, P: 0xd8a878, E: 0x111111, W: 0xf0f0f0, T: 0x2a8a8a, L: 0x223344 },
      map: [
        '...HHHHHH...',
        '..HHHHHHHH..',
        '..HPPPPPPH..',
        '..HPEPPEPH..',
        '..HPPPPPPH..',
        '...PPPPPP...',
        '..PWWWWWWP..',
        '.TPWWWWWWPT.',
        '.PTWWWWWWTP.',
        '.PPWWWWWWPP.',
        '...LL..LL...',
        '...WW..WW...',
      ],
    },
    chamana: {
      pal: { V: 0x8a2be2, v: 0x5a1c99, P: 0xd8b890, E: 0x111111, G: 0xffd700, R: 0xcc2244 },
      map: [
        '...VVVVVV...',
        '..VVVVVVVV..',
        '..VPPPPPPV..',
        '..GPEPPEPG..',
        '..VPPPPPPV..',
        '...PPPPPP...',
        '..RRRRRRRR..',
        '.RVRRRRRRVR.',
        '.RRRGGGGRRR.',
        '.RVRRRRRRVR.',
        '..RRRRRRRR..',
        '...RR..RR...',
      ],
    },
    gato: {
      pal: { N: 0x2a2a33, n: 0x44444f, W: 0xffffff, E: 0x7fff00, P: 0xff99aa },
      map: [
        '..N......N..',
        '..NN....NN..',
        '..NNNNNNNN..',
        '..NENNNNEN..',
        '..NNNPPNNN..',
        '...NNNNNN...',
        '..NNNNNNNN..',
        '.NNNNNNNNNN.',
        '.NNNNNNNNNn.',
        '.NnNNNNNNn.W',
        '..NN..NN...W',
        '...........W',
      ],
    },
    elvis: {
      pal: { K: 0x111118, P: 0xe8b88a, W: 0xf4f4f8, w: 0xd0d0da, G: 0xffd700, E: 0x111111 },
      map: [
        '....KKKK....',
        '...KKKKKK...',
        '..KKKKKKKK..',
        '..KPPPPPPK..',
        '..KEEPPEEK..',
        '...PPPPPP...',
        '..WWWWWWWW..',
        '.WwWGGGGWwW.',
        '.WWWWGGWWWW.',
        '.WwWWWWWWwW.',
        '..WWWWWWWW..',
        '...WW..WW...',
      ],
    },
    // ---- Ítems ----
    corazon: {
      pal: { R: 0xff3355, r: 0xcc1133, W: 0xff99aa },
      map: [
        '..RR..RR..',
        '.RWRR.RRR.',
        'RWWRRRRRRr',
        'RWRRRRRRRr',
        'RRRRRRRRRr',
        '.RRRRRRRr.',
        '..RRRRRr..',
        '...RRRr...',
        '....Rr....',
      ],
    },
    moneda: {
      pal: { G: 0xffd700, g: 0xb8860b, W: 0xfff2b3 },
      map: [
        '...GGGG...',
        '..GGGGGG..',
        '.GGWggGGG.',
        '.GWgGGgGG.',
        '.GWgGGgGG.',
        '.GGGggGGG.',
        '..GGGGGG..',
        '...GGGG...',
      ],
    },
    pocion: {
      pal: { G: 0x44cc44, g: 0x2a8a2a, M: 0xb35a2a, m: 0x8a4220 },
      map: [
        '....G.....',
        '..GGGG.G..',
        '.GGgGGGG..',
        '..GGgGG...',
        '...GGG....',
        '..MMMMMM..',
        '..MmmmmM..',
        '...MMMM...',
        '...mmmm...',
      ],
    },
    espada: {
      pal: { S: 0xd7e3ea, s: 0x9fb3c0, G: 0xffaa00, M: 0x6b4a2b },
      map: [
        '.......SS.',
        '......SsS.',
        '.....SsS..',
        '....SsS...',
        '...SsS....',
        '..GSS.....',
        '.MGG......',
        'MM.G......',
      ],
    },
    arco: {
      pal: { B: 0x8a5a2b, b: 0x6b4220, A: 0xd7e3ea, S: 0xcccccc },
      map: [
        '.B....S...',
        '..B...S...',
        '...B..A...',
        '...B.AAA..',
        '...BAAAAA.',
        '...B.AAA..',
        '...B..A...',
        '..B...S...',
        '.B....S...',
      ],
    },
    escudo: {
      pal: { B: 0xffd700, A: 0x9d6bff, a: 0x6a44b8 },
      map: [
        '.BBBBBBBB.',
        '.BAAAAAAB.',
        '.BAAaaAAB.',
        '.BAaAAaAB.',
        '.BAAAAAAB.',
        '.BAAAAAAB.',
        '..BAAAAB..',
        '...BAAB...',
        '....BB....',
      ],
    },
    mate: {
      pal: { B: 0xc0c0c0, M: 0x7a4f2a, m: 0x5d3a1e, Y: 0x88ff66 },
      map: [
        '......B...',
        '.....B....',
        '.....B....',
        '...MMYM...',
        '..MMMMMM..',
        '..MmMMmM..',
        '..MMMMMM..',
        '...MMMM...',
      ],
    },
    mateOro: {
      pal: { B: 0xffffff, M: 0xffd700, m: 0xcc9900, Y: 0x00ffc8 },
      map: [
        '......B...',
        '.....B....',
        '.....B....',
        '...MMYM...',
        '..MMMMMM..',
        '..MmMMmM..',
        '..MMMMMM..',
        '...MMMM...',
      ],
    },
    bfg: {
      pal: { M: 0x4a5d3a, m: 0x36452a, K: 0x111111, R: 0xcc2222, Y: 0xffe14d },
      map: [
        '..........',
        'KMMMMMMMMK',
        'MMmmmmmmMM',
        'MRMMMMMMYM',
        'MMmmmmmmMM',
        'KMMMMMMMMK',
        '...KK.....',
        '...KK.....',
        '..KKK.....',
      ],
    },
    tequila: {
      pal: { V: [0x88ddcc, 0.85], v: 0x55aa99, A: 0xffe680, L: 0xddaa33, S: 0xffffff },
      map: [
        '....SS....',
        '....LL....',
        '....VV....',
        '...VAAV...',
        '...VAAV...',
        '..VAAAAV..',
        '..VAAAAV..',
        '..vAAAAv..',
        '...vvvv...',
      ],
    },
    mimic: {
      pal: { C: 0x2a2a33, c: 0x17171f, G: 0xb8c4d0, W: 0xffffff, R: 0x661111, E: 0xff2222 },
      map: [
        '.CCCCCCCC.',
        '.CGEGGEGC.',
        '.CWCWCWCC.',
        '.RRRRRRRR.',
        '.CWCCWCCW.',
        '.CCCCCCCC.',
        '.CCCCCCCC.',
        '.cccccccc.',
      ],
    },
    cofre: {
      pal: { C: 0x2a2a33, c: 0x17171f, G: 0xb8c4d0 },
      map: [
        '.CCCCCCCC.',
        '.CGGGGGGC.',
        '.CCCCCCCC.',
        '.GGGGGGGG.',
        '.CCCGGCCC.',
        '.CCCGGCCC.',
        '.CCCCCCCC.',
        '.cccccccc.',
      ],
    },
    pinchos: {
      pal: { A: 0xb0bec5, a: 0x78909c },
      map: [
        '..........',
        '..........',
        '..........',
        '..A...A...',
        '..A...A..A',
        '.AAA.AAA.A',
        '.AaA.AaA.A',
        'AAAAAAAAAA',
      ],
    },
    barril: {
      pal: { R: 0xcc3322, r: 0x992211, M: 0x444455, W: 0xffeecc },
      map: [
        '..RRRRRR..',
        '.RRRRRRRR.',
        '.MMMMMMMM.',
        '.RRRWWRRR.',
        '.RRWWWWRR.',
        '.RRRWWRRR.',
        '.MMMMMMMM.',
        '.RRRRRRRR.',
        '..rrrrrr..',
      ],
    },
    altar: {
      pal: { M: 0x333340, m: 0x4a4a58, K: 0x111111, W: 0xf0f0e8, P: 0xe8d8a0 },
      map: [
        '..PPPPPP..',
        '..PPPPPP..',
        '.MMMMMMMM.',
        '.MmmmmmmM.',
        '.MKWKWKWM.',
        '.MWKWKWKM.',
        '.MMMMMMMM.',
        '.mMMMMMMm.',
      ],
    },
    granadaFrag: {
      pal: { V: 0x3a7d44, v: 0x2a5d32, M: 0x555555, X: 0x222222 },
      map: [
        '....MX....',
        '...MMM....',
        '..XMMMX...',
        '..VVVVVV..',
        '.VvVVVVvV.',
        '.VVXVVXVV.',
        '.VvVVVVvV.',
        '..VVVVVV..',
        '...vvvv...',
      ],
    },
    granadaMolotov: {
      pal: { G: 0x88bb55, B: [0xcfe8ff, 0.8], F: 0xff7722, f: 0xffcc33, R: 0xcc2200 },
      map: [
        '....F.....',
        '....f.....',
        '...RRR....',
        '...GBG....',
        '..GBBBG...',
        '.GBBBBBG..',
        '.GBfFfBG..',
        '.GBBBBBG..',
        '..GBBBG...',
        '...GGG....',
      ],
    },
    granadaStun: {
      pal: { Y: 0xffe14d, y: 0xccaa22, W: 0xffffff, M: 0x444444 },
      map: [
        '...MMMM...',
        '..MYYYYM..',
        '.MYWYYWYM.',
        '.MYYYYYYM.',
        '.MYWYYWYM.',
        '.MYYYYYYM.',
        '..MYYYYM..',
        '...MMMM...',
        '..y....y..',
      ],
    },
    ametralladora: {
      pal: { M: 0x33373f, m: 0x4a4f59, D: 0x22252b, B: 0x88909c, X: 0x111111 },
      map: [
        '..........',
        '.MMMMMM...',
        '.MmmmmM.B.',
        'XDDDDDMMB.',
        '.MMMMMmB..',
        '..M.XMB...',
        '..MMX.....',
        '..DDD.....',
        '..DDD.....',
      ],
    },
    reticle: {
      pal: { R: 0xff3344 },
      map: [
        'RRR....RRR',
        'R........R',
        'R...RR...R',
        '....RR....',
        '....RR....',
        'R...RR...R',
        'R........R',
        'RRR....RRR',
      ],
    },
    fuego: {
      pal: { R: 0xff3300, O: 0xff7711, Y: 0xffcc33, y: [0xffee66, 0.9] },
      map: [
        '...Y..Y...',
        '..YyO.yY..',
        '.YOOOYOOY.',
        '.OORROOOO.',
        'OORRRRROOO',
        'ORRRRRRROO',
        '.ORRRRRO..',
        '..OORRO...',
        '...OOO....',
      ],
    },
    vidaExtra: {
      pal: { G: 0xffd700, g: 0xcc9900, N: 0x1a1a1a, W: 0xfff2b3 },
      map: [
        '..GG..GG..',
        '.GggGGggG.',
        'GgWgggggGG',
        'GgNgggNgGG',
        'GggggggggG',
        '.GgNNNNgG.',
        '..GggggG..',
        '...GggG...',
        '....GG....',
      ],
    },
    altarVida: {
      pal: { S: 0xb8860b, s: 0x8a5a1e, R: 0xff3355, r: 0xcc1133, G: 0xffd700, W: 0xfff2b3 },
      map: [
        '...RRRR...',
        '..RWRRWR..',
        '..RRRRRR..',
        '...RRRR...',
        '....RR....',
        '...GGGG...',
        '..GSSSSG..',
        '..SssssS..',
        '.SSSSSSSS.',
        '.sSSSSSSs.',
      ],
    },
    mapa: {
      pal: { P: 0xe8d8a0, p: 0xc8b070, L: 0x8a5a2b, R: 0xcc3322, X: 0x993322 },
      map: [
        'LPPPPPPPPL',
        'LPpPPpPPPL',
        'LPPLLPPpPL',
        'LpPPLPPPPL',
        'LPPpPLLPPL',
        'LPPPPpPRXL',
        'LpPPpPPXRL',
        'LPPPpPPpPL',
        'LpPPPpPPPL',
        'LPPPPPPpPL',
      ],
    },
    anillo: {
      pal: { G: 0xffd700, D: 0x00e5ff, W: 0xccf6ff },
      map: [
        '....DW....',
        '...DDDD...',
        '....DD....',
        '...G..G...',
        '..G....G..',
        '..G....G..',
        '...G..G...',
        '....GG....',
      ],
    },
  };

  // Rasteriza todos los mapas a texturas (una sola vez, al inicio).
  MZ.buildSpriteTextures = function (renderer) {
    const out = {};
    for (const [name, def] of Object.entries(MZ.PIXEL_SPRITES)) {
      const g = new PIXI.Graphics();
      const w = def.map[0].length, h = def.map.length;
      def.map.forEach((row, y) => {
        for (let x = 0; x < row.length; x++) {
          const c = def.pal[row[x]];
          if (c == null) continue;
          if (Array.isArray(c)) g.rect(x, y, 1, 1).fill({ color: c[0], alpha: c[1] });
          else g.rect(x, y, 1, 1).fill(c);
        }
      });
      const tex = renderer.generateTexture({ target: g, frame: new PIXI.Rectangle(0, 0, w, h) });
      tex.source.scaleMode = 'nearest';
      out[name] = tex;
    }
    return out;
  };
})();
